/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellWeightBalanceRouteImport } from './routes/_shell.weight-balance'
import { Route as ShellStructuresRouteImport } from './routes/_shell.structures'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellPropulsionRouteImport } from './routes/_shell.propulsion'
import { Route as ShellProjectsRouteImport } from './routes/_shell.projects'
import { Route as ShellPerformanceRouteImport } from './routes/_shell.performance'
import { Route as ShellOptimizationRouteImport } from './routes/_shell.optimization'
import { Route as ShellMissionRouteImport } from './routes/_shell.mission'
import { Route as ShellLibraryRouteImport } from './routes/_shell.library'
import { Route as ShellFuelRouteImport } from './routes/_shell.fuel'
import { Route as ShellFlightDynamicsRouteImport } from './routes/_shell.flight-dynamics'
import { Route as ShellDigitalTwinRouteImport } from './routes/_shell.digital-twin'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellConfigurationRouteImport } from './routes/_shell.configuration'
import { Route as ShellCfdRouteImport } from './routes/_shell.cfd'
import { Route as ShellAiAssistantRouteImport } from './routes/_shell.ai-assistant'
import { Route as ShellAerodynamicsRouteImport } from './routes/_shell.aerodynamics'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellWeightBalanceRoute = ShellWeightBalanceRouteImport.update({
  id: '/weight-balance',
  path: '/weight-balance',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStructuresRoute = ShellStructuresRouteImport.update({
  id: '/structures',
  path: '/structures',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPropulsionRoute = ShellPropulsionRouteImport.update({
  id: '/propulsion',
  path: '/propulsion',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsRoute = ShellProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPerformanceRoute = ShellPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOptimizationRoute = ShellOptimizationRouteImport.update({
  id: '/optimization',
  path: '/optimization',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMissionRoute = ShellMissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLibraryRoute = ShellLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFuelRoute = ShellFuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFlightDynamicsRoute = ShellFlightDynamicsRouteImport.update({
  id: '/flight-dynamics',
  path: '/flight-dynamics',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDigitalTwinRoute = ShellDigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConfigurationRoute = ShellConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCfdRoute = ShellCfdRouteImport.update({
  id: '/cfd',
  path: '/cfd',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAiAssistantRoute = ShellAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAerodynamicsRoute = ShellAerodynamicsRouteImport.update({
  id: '/aerodynamics',
  path: '/aerodynamics',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aerodynamics': typeof ShellAerodynamicsRoute
  '/ai-assistant': typeof ShellAiAssistantRoute
  '/cfd': typeof ShellCfdRoute
  '/configuration': typeof ShellConfigurationRoute
  '/dashboard': typeof ShellDashboardRoute
  '/digital-twin': typeof ShellDigitalTwinRoute
  '/flight-dynamics': typeof ShellFlightDynamicsRoute
  '/fuel': typeof ShellFuelRoute
  '/library': typeof ShellLibraryRoute
  '/mission': typeof ShellMissionRoute
  '/optimization': typeof ShellOptimizationRoute
  '/performance': typeof ShellPerformanceRoute
  '/projects': typeof ShellProjectsRoute
  '/propulsion': typeof ShellPropulsionRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/structures': typeof ShellStructuresRoute
  '/weight-balance': typeof ShellWeightBalanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aerodynamics': typeof ShellAerodynamicsRoute
  '/ai-assistant': typeof ShellAiAssistantRoute
  '/cfd': typeof ShellCfdRoute
  '/configuration': typeof ShellConfigurationRoute
  '/dashboard': typeof ShellDashboardRoute
  '/digital-twin': typeof ShellDigitalTwinRoute
  '/flight-dynamics': typeof ShellFlightDynamicsRoute
  '/fuel': typeof ShellFuelRoute
  '/library': typeof ShellLibraryRoute
  '/mission': typeof ShellMissionRoute
  '/optimization': typeof ShellOptimizationRoute
  '/performance': typeof ShellPerformanceRoute
  '/projects': typeof ShellProjectsRoute
  '/propulsion': typeof ShellPropulsionRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/structures': typeof ShellStructuresRoute
  '/weight-balance': typeof ShellWeightBalanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/aerodynamics': typeof ShellAerodynamicsRoute
  '/_shell/ai-assistant': typeof ShellAiAssistantRoute
  '/_shell/cfd': typeof ShellCfdRoute
  '/_shell/configuration': typeof ShellConfigurationRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/digital-twin': typeof ShellDigitalTwinRoute
  '/_shell/flight-dynamics': typeof ShellFlightDynamicsRoute
  '/_shell/fuel': typeof ShellFuelRoute
  '/_shell/library': typeof ShellLibraryRoute
  '/_shell/mission': typeof ShellMissionRoute
  '/_shell/optimization': typeof ShellOptimizationRoute
  '/_shell/performance': typeof ShellPerformanceRoute
  '/_shell/projects': typeof ShellProjectsRoute
  '/_shell/propulsion': typeof ShellPropulsionRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/structures': typeof ShellStructuresRoute
  '/_shell/weight-balance': typeof ShellWeightBalanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aerodynamics'
    | '/ai-assistant'
    | '/cfd'
    | '/configuration'
    | '/dashboard'
    | '/digital-twin'
    | '/flight-dynamics'
    | '/fuel'
    | '/library'
    | '/mission'
    | '/optimization'
    | '/performance'
    | '/projects'
    | '/propulsion'
    | '/reports'
    | '/settings'
    | '/structures'
    | '/weight-balance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aerodynamics'
    | '/ai-assistant'
    | '/cfd'
    | '/configuration'
    | '/dashboard'
    | '/digital-twin'
    | '/flight-dynamics'
    | '/fuel'
    | '/library'
    | '/mission'
    | '/optimization'
    | '/performance'
    | '/projects'
    | '/propulsion'
    | '/reports'
    | '/settings'
    | '/structures'
    | '/weight-balance'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/aerodynamics'
    | '/_shell/ai-assistant'
    | '/_shell/cfd'
    | '/_shell/configuration'
    | '/_shell/dashboard'
    | '/_shell/digital-twin'
    | '/_shell/flight-dynamics'
    | '/_shell/fuel'
    | '/_shell/library'
    | '/_shell/mission'
    | '/_shell/optimization'
    | '/_shell/performance'
    | '/_shell/projects'
    | '/_shell/propulsion'
    | '/_shell/reports'
    | '/_shell/settings'
    | '/_shell/structures'
    | '/_shell/weight-balance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/weight-balance': {
      id: '/_shell/weight-balance'
      path: '/weight-balance'
      fullPath: '/weight-balance'
      preLoaderRoute: typeof ShellWeightBalanceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/structures': {
      id: '/_shell/structures'
      path: '/structures'
      fullPath: '/structures'
      preLoaderRoute: typeof ShellStructuresRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/propulsion': {
      id: '/_shell/propulsion'
      path: '/propulsion'
      fullPath: '/propulsion'
      preLoaderRoute: typeof ShellPropulsionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects': {
      id: '/_shell/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ShellProjectsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/performance': {
      id: '/_shell/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof ShellPerformanceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/optimization': {
      id: '/_shell/optimization'
      path: '/optimization'
      fullPath: '/optimization'
      preLoaderRoute: typeof ShellOptimizationRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/mission': {
      id: '/_shell/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof ShellMissionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/library': {
      id: '/_shell/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ShellLibraryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/fuel': {
      id: '/_shell/fuel'
      path: '/fuel'
      fullPath: '/fuel'
      preLoaderRoute: typeof ShellFuelRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/flight-dynamics': {
      id: '/_shell/flight-dynamics'
      path: '/flight-dynamics'
      fullPath: '/flight-dynamics'
      preLoaderRoute: typeof ShellFlightDynamicsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/digital-twin': {
      id: '/_shell/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof ShellDigitalTwinRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/configuration': {
      id: '/_shell/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ShellConfigurationRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/cfd': {
      id: '/_shell/cfd'
      path: '/cfd'
      fullPath: '/cfd'
      preLoaderRoute: typeof ShellCfdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/ai-assistant': {
      id: '/_shell/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof ShellAiAssistantRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/aerodynamics': {
      id: '/_shell/aerodynamics'
      path: '/aerodynamics'
      fullPath: '/aerodynamics'
      preLoaderRoute: typeof ShellAerodynamicsRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAerodynamicsRoute: typeof ShellAerodynamicsRoute
  ShellAiAssistantRoute: typeof ShellAiAssistantRoute
  ShellCfdRoute: typeof ShellCfdRoute
  ShellConfigurationRoute: typeof ShellConfigurationRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellDigitalTwinRoute: typeof ShellDigitalTwinRoute
  ShellFlightDynamicsRoute: typeof ShellFlightDynamicsRoute
  ShellFuelRoute: typeof ShellFuelRoute
  ShellLibraryRoute: typeof ShellLibraryRoute
  ShellMissionRoute: typeof ShellMissionRoute
  ShellOptimizationRoute: typeof ShellOptimizationRoute
  ShellPerformanceRoute: typeof ShellPerformanceRoute
  ShellProjectsRoute: typeof ShellProjectsRoute
  ShellPropulsionRoute: typeof ShellPropulsionRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellStructuresRoute: typeof ShellStructuresRoute
  ShellWeightBalanceRoute: typeof ShellWeightBalanceRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAerodynamicsRoute: ShellAerodynamicsRoute,
  ShellAiAssistantRoute: ShellAiAssistantRoute,
  ShellCfdRoute: ShellCfdRoute,
  ShellConfigurationRoute: ShellConfigurationRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellDigitalTwinRoute: ShellDigitalTwinRoute,
  ShellFlightDynamicsRoute: ShellFlightDynamicsRoute,
  ShellFuelRoute: ShellFuelRoute,
  ShellLibraryRoute: ShellLibraryRoute,
  ShellMissionRoute: ShellMissionRoute,
  ShellOptimizationRoute: ShellOptimizationRoute,
  ShellPerformanceRoute: ShellPerformanceRoute,
  ShellProjectsRoute: ShellProjectsRoute,
  ShellPropulsionRoute: ShellPropulsionRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellStructuresRoute: ShellStructuresRoute,
  ShellWeightBalanceRoute: ShellWeightBalanceRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
